---
name: 01 Azure Landing Zones Continuous Integration
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate_and_plan:
    uses: ${organization_name}/${repository_name_templates}/${ci_template_path}@main
    name: 'CI'
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    with:
      root_module_folder_relative_path: '${root_module_folder_relative_path}'
